vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        user:
            uri_prefix: /assets/profile
            upload_destination: '%kernel.project_dir%/public/assets/profile'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true